<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>KairosSpot</AssemblyName>
    <RootNamespace>KairosSpot</RootNamespace>
    <Version>1.0.0</Version>
    <Product>KaiSpot</Product>
    <Company>Kairos</Company>
  </PropertyGroup>

</Project>
